# Generated by Django 3.2.5 on 2021-08-26 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cityweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityweather',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 9, 35, 28, 809005, tzinfo=utc)),
        ),
    ]
