# Generated by Django 4.0.6 on 2022-07-19 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cityweather_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweather',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 11, 46, 15, 591794, tzinfo=utc)),
        ),
    ]
